name: Deploy AI Infrastructure


on:

  workflow_dispatch:



permissions:

  contents: read

  id-token: write



jobs:


 deploy:


  runs-on: ubuntu-latest



  env:

    AWS_REGION: us-east-1



  defaults:


    run:


      shell: bash


      working-directory: environments/ai



  steps:



  - name: Checkout

    uses: actions/checkout@v5



  - name: AWS Credentials

    uses: aws-actions/configure-aws-credentials@v4


    with:


      role-to-assume: arn:aws:iam::127214183643:role/github-actions-terraform-role


      aws-region: ${{ env.AWS_REGION }}



  - name: Setup Terraform

    uses: hashicorp/setup-terraform@v3



  - name: Terraform Init

    run:

      terraform init



  - name: Terraform Apply

    run:

      terraform apply -auto-approve
