name: Infrastructure AI Review


on:

  workflow_call:

  workflow_dispatch:



permissions:

  contents: read

  id-token: write



jobs:


  review:


    name: Terraform Infrastructure Review


    runs-on: ubuntu-latest



    steps:



      - name: Checkout repository

        uses: actions/checkout@v5





      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          role-to-assume: arn:aws:iam::127214183643:role/github-actions-terraform-role

          aws-region: us-east-1

          role-duration-seconds: 7200





      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3





      - name: Install Trivy

        run: |

          sudo apt-get update

          sudo apt-get install -y wget gnupg


          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
          | sudo gpg --dearmor \
          -o /usr/share/keyrings/trivy.gpg


          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] \
          https://aquasecurity.github.io/trivy-repo/deb generic main" \
          | sudo tee /etc/apt/sources.list.d/trivy.list


          sudo apt-get update

          sudo apt-get install trivy -y





      - name: Prepare AI Results directory

        run: |

          mkdir -p ai-results





      - name: Terraform Verification

        shell: bash

        env:

          TF_STATE_BUCKET_NAME: "terraform-state-17062026"

          TF_STATE_BUCKET_REGION: eu-central-1


        run: |


          chmod +x scripts/deployment-automation-scripts/terraform-verify.sh


          ./scripts/deployment-automation-scripts/terraform-verify.sh





      - name: Run Trivy Terraform Scan

        shell: bash

        run: |


          trivy config ./environments \
          --format json \
          --output ai-results/trivy-results.json





      - name: Upload Infrastructure Review Results

        uses: actions/upload-artifact@v4


        with:


          name: infrastructure-review-results


          path: ai-results/
